# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/cfg/clocks.xdc

# XDC: imports/cfg/ports.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_dac_0_0/system_axis_red_pitaya_dac_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/system/ip/system_dds_compiler_0_0/system_dds_compiler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dds_compiler_0_0 || ORIG_REF_NAME==system_dds_compiler_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_constant_0_0/system_axis_constant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_constant_0_0 || ORIG_REF_NAME==system_axis_constant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_1/system_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_0_1 || ORIG_REF_NAME==system_xlslice_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_2/system_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_2 || ORIG_REF_NAME==system_axi_gpio_0_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] -quiet

# IP: bd/system/ip/system_Control_and_Nca_0/system_Control_and_Nca_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_Control_and_Nca_0 || ORIG_REF_NAME==system_Control_and_Nca_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_4/system_xlslice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_0_4 || ORIG_REF_NAME==system_xlslice_0_4} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_5/system_xlslice_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_0_5 || ORIG_REF_NAME==system_xlslice_0_5} -quiet] -quiet

# IP: bd/system/ip/system_res_fase_up_1/system_res_fase_up_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_res_fase_up_1 || ORIG_REF_NAME==system_res_fase_up_1} -quiet] -quiet

# IP: bd/system/ip/system_res_fase_up_0/system_res_fase_up_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_res_fase_up_0 || ORIG_REF_NAME==system_res_fase_up_0} -quiet] -quiet

# IP: bd/system/ip/system_result_cuad_0/system_result_cuad_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_result_cuad_0 || ORIG_REF_NAME==system_result_cuad_0} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_3/system_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_0_3 || ORIG_REF_NAME==system_xlslice_0_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_3 || ORIG_REF_NAME==system_axi_gpio_0_3} -quiet] -quiet

# IP: bd/system/ip/system_M_and_Nma_0/system_M_and_Nma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_M_and_Nma_0 || ORIG_REF_NAME==system_M_and_Nma_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_fifo_mm_s_0_0/system_axi_fifo_mm_s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==system_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_clock_converter_0_1/system_axis_clock_converter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_clock_converter_0_1 || ORIG_REF_NAME==system_axis_clock_converter_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axis_red_pitaya_adc_0_0/system_axis_red_pitaya_adc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_red_pitaya_adc_0_0 || ORIG_REF_NAME==system_axis_red_pitaya_adc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_split_0_0/system_signal_split_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_split_0_0 || ORIG_REF_NAME==system_signal_split_0_0} -quiet] -quiet

# IP: bd/system/ip/system_drive_gpios_0_0/system_drive_gpios_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_drive_gpios_0_0 || ORIG_REF_NAME==system_drive_gpios_0_0} -quiet] -quiet

# IP: bd/system/ip/system_drive_gpios_0_1/system_drive_gpios_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_drive_gpios_0_1 || ORIG_REF_NAME==system_drive_gpios_0_1} -quiet] -quiet

# IP: bd/system/ip/system_drive_leds_0_0/system_drive_leds_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_drive_leds_0_0 || ORIG_REF_NAME==system_drive_leds_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_constant_0_1/system_axis_constant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_constant_0_1 || ORIG_REF_NAME==system_axis_constant_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_1_0/system_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_1_0 || ORIG_REF_NAME==system_xlslice_1_0} -quiet] -quiet

# IP: bd/system/ip/system_dds_compiler_0_1/system_dds_compiler_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_dds_compiler_0_1 || ORIG_REF_NAME==system_dds_compiler_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlslice_0_6/system_xlslice_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xlslice_0_6 || ORIG_REF_NAME==system_xlslice_0_6} -quiet] -quiet

# IP: bd/system/ip/system_start_signal_generat_0_0/system_start_signal_generat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_start_signal_generat_0_0 || ORIG_REF_NAME==system_start_signal_generat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_and_2_1_0/system_and_2_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_and_2_1_0 || ORIG_REF_NAME==system_and_2_1_0} -quiet] -quiet

# IP: bd/system/ip/system_delay_axi_streaming_0_0/system_delay_axi_streaming_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_delay_axi_streaming_0_0 || ORIG_REF_NAME==system_delay_axi_streaming_0_0} -quiet] -quiet

# IP: bd/system/ip/system_delay_axi_streaming_1_0/system_delay_axi_streaming_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_delay_axi_streaming_1_0 || ORIG_REF_NAME==system_delay_axi_streaming_1_0} -quiet] -quiet

# IP: bd/system/ip/system_and_2_0_0/system_and_2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_and_2_0_0 || ORIG_REF_NAME==system_and_2_0_0} -quiet] -quiet

# IP: bd/system/ip/system_signal_processing_LI_0_0/system_signal_processing_LI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_signal_processing_LI_0_0 || ORIG_REF_NAME==system_signal_processing_LI_0_0} -quiet] -quiet

# IP: bd/system/ip/system_decimator_0_0/system_decimator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_decimator_0_0 || ORIG_REF_NAME==system_decimator_0_0} -quiet] -quiet

# IP: bd/system/ip/system_selector_data_in_0/system_selector_data_in_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_selector_data_in_0 || ORIG_REF_NAME==system_selector_data_in_0} -quiet] -quiet

# IP: bd/system/ip/system_linear_mean_0_0/system_linear_mean_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_linear_mean_0_0 || ORIG_REF_NAME==system_linear_mean_0_0} -quiet] -quiet

# IP: bd/system/ip/system_mux_0_0/system_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_mux_0_0 || ORIG_REF_NAME==system_mux_0_0} -quiet] -quiet

# IP: bd/system/ip/system_finished_and_decimator_method_0/system_finished_and_decimator_method_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_finished_and_decimator_method_0 || ORIG_REF_NAME==system_finished_and_decimator_method_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ds_buf_1_0 || ORIG_REF_NAME==system_util_ds_buf_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_util_ds_buf_1_0/system_util_ds_buf_1_0_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ds_buf_2_0 || ORIG_REF_NAME==system_util_ds_buf_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_2/system_axi_gpio_0_2_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_2 || ORIG_REF_NAME==system_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_2/system_axi_gpio_0_2_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_2/system_axi_gpio_0_2.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_2 || ORIG_REF_NAME==system_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_1/system_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_1 || ORIG_REF_NAME==system_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_Control_and_Nca_0/system_Control_and_Nca_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_Control_and_Nca_0 || ORIG_REF_NAME==system_Control_and_Nca_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_Control_and_Nca_0/system_Control_and_Nca_0_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_Control_and_Nca_0/system_Control_and_Nca_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_Control_and_Nca_0 || ORIG_REF_NAME==system_Control_and_Nca_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_result_cuad_0/system_result_cuad_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_result_cuad_0 || ORIG_REF_NAME==system_result_cuad_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_result_cuad_0/system_result_cuad_0_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_result_cuad_0/system_result_cuad_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_result_cuad_0 || ORIG_REF_NAME==system_result_cuad_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_3 || ORIG_REF_NAME==system_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axi_gpio_0_3/system_axi_gpio_0_3.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_3 || ORIG_REF_NAME==system_axi_gpio_0_3} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_M_and_Nma_0/system_M_and_Nma_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_M_and_Nma_0 || ORIG_REF_NAME==system_M_and_Nma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_M_and_Nma_0/system_M_and_Nma_0_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_M_and_Nma_0/system_M_and_Nma_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_M_and_Nma_0 || ORIG_REF_NAME==system_M_and_Nma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_rst_ps7_0_125M_0/system_rst_ps7_0_125M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_125M_0 || ORIG_REF_NAME==system_rst_ps7_0_125M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_axis_clock_converter_0_1/system_axis_clock_converter_0_1_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_finished_and_decimator_method_0/system_finished_and_decimator_method_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_finished_and_decimator_method_0 || ORIG_REF_NAME==system_finished_and_decimator_method_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_finished_and_decimator_method_0/system_finished_and_decimator_method_0_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_finished_and_decimator_method_0/system_finished_and_decimator_method_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_finished_and_decimator_method_0 || ORIG_REF_NAME==system_finished_and_decimator_method_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: c:/Users/MatiOliva/Documents/00-lockin_redpitaya/hardware/lockin.gen/sources_1/bd/system/system_ooc.xdc
